Repository hmcts/div-validation-service, pull requests merged in 2019-05, with the labels that each got.

#59 Only enable notifications on master
  Jenkinsfile_CNP
Labels: ns:div-vs-pr-59

#60 Force Tomcat Version to more secure one
  build.gradle
Labels: ns:div-vs-pr-60

#62 Upgraded jackson version to fix CVE
  build.gradle
Labels: ns:div-vs-pr-62

#61 DIV-4835 : Fix PMD/checkstyle warnings
  build.gradle
  ruleset.xml
Labels: ns:div-vs-pr-61
