Repository hmcts/div-validation-service, pull requests merged in 2019-01, with the labels that each got.

#45 Added temporal suppression CVE-2018-8088
  dependency-check-suppressions.xml
Labels: ns:div-vs-pr-45

#46 Move to shared ASP 1
  infrastructure/main.tf
Labels: ns:div-vs-pr-46

#48 DIV-3814 - removed dependency check suppression for CVE-2018-8088
  dependency-check-suppressions.xml
Labels: ns:div-vs-pr-48

#47 Revert to normal ASP
  infrastructure/main.tf
Labels: ns:div-vs-pr-47

#49 [PREVIEW] Set java logging version to 4.0.1
  build.gradle
  src/main/java/uk/gov/hmcts/reform/divorce/validationservice/ValidationServiceApplication.java
  src/main/java/uk/gov/hmcts/reform/divorce/validationservice/insights/AppInsights.java
  src/test/java/uk/gov/hmcts/reform/divorce/validationservice/insights/AppInsightsUTest.java
Labels: ns:div-vs-pr-49
