Repository hmcts/div-validation-service, pull requests merged in 2019-06, with the labels that each got.

#64 Set instance size to I3
  infrastructure/main.tf
Labels: ns:div-vs-pr-64

#65 Adjust instance size by var
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-vs-pr-65

#63 DIV-4484 upgrade gradle version to 5.x
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:div-vs-pr-63

#66 DIV-5056: OWASP upgrade
  build.gradle
  checkstyle.xml
  src/test/java/uk/gov/hmcts/reform/divorce/validationservice/controller/ValidationServiceControllerTest.java
Labels: ns:div-vs-pr-66

#68 Update demo with master - demoupdate
  build.gradle
  checkstyle.xml
  src/test/java/uk/gov/hmcts/reform/divorce/validationservice/controller/ValidationServiceControllerTest.java
Labels: ns:div-vs-pr-68

#67 DIV-3264: Update readme and added license file
  LICENSE.md
  README.md
Labels: ns:div-vs-pr-67
